//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetAll.GetAllService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetAllService.IGetAll")]
    public interface IGetAll {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetAll/GetNumberOfWorkers", ReplyAction="http://tempuri.org/IGetAll/GetNumberOfWorkersResponse")]
        int GetNumberOfWorkers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetAll/GetNumberOfWorkers", ReplyAction="http://tempuri.org/IGetAll/GetNumberOfWorkersResponse")]
        System.Threading.Tasks.Task<int> GetNumberOfWorkersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetAll/FindTheNumberOfEmployeesInDepartment", ReplyAction="http://tempuri.org/IGetAll/FindTheNumberOfEmployeesInDepartmentResponse")]
        int FindTheNumberOfEmployeesInDepartment(string nameOfDepartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetAll/FindTheNumberOfEmployeesInDepartment", ReplyAction="http://tempuri.org/IGetAll/FindTheNumberOfEmployeesInDepartmentResponse")]
        System.Threading.Tasks.Task<int> FindTheNumberOfEmployeesInDepartmentAsync(string nameOfDepartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetAll/GetAllWorker", ReplyAction="http://tempuri.org/IGetAll/GetAllWorkerResponse")]
        System.Data.DataTable GetAllWorker();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetAll/GetAllWorker", ReplyAction="http://tempuri.org/IGetAll/GetAllWorkerResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllWorkerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetAll/GetAllWorkerByDepartment", ReplyAction="http://tempuri.org/IGetAll/GetAllWorkerByDepartmentResponse")]
        System.Data.DataTable GetAllWorkerByDepartment(string departmentName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetAll/GetAllWorkerByDepartment", ReplyAction="http://tempuri.org/IGetAll/GetAllWorkerByDepartmentResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllWorkerByDepartmentAsync(string departmentName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetAllChannel : GetAll.GetAllService.IGetAll, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllClient : System.ServiceModel.ClientBase<GetAll.GetAllService.IGetAll>, GetAll.GetAllService.IGetAll {
        
        public GetAllClient() {
        }
        
        public GetAllClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetAllClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetAllClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetAllClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetNumberOfWorkers() {
            return base.Channel.GetNumberOfWorkers();
        }
        
        public System.Threading.Tasks.Task<int> GetNumberOfWorkersAsync() {
            return base.Channel.GetNumberOfWorkersAsync();
        }
        
        public int FindTheNumberOfEmployeesInDepartment(string nameOfDepartment) {
            return base.Channel.FindTheNumberOfEmployeesInDepartment(nameOfDepartment);
        }
        
        public System.Threading.Tasks.Task<int> FindTheNumberOfEmployeesInDepartmentAsync(string nameOfDepartment) {
            return base.Channel.FindTheNumberOfEmployeesInDepartmentAsync(nameOfDepartment);
        }
        
        public System.Data.DataTable GetAllWorker() {
            return base.Channel.GetAllWorker();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllWorkerAsync() {
            return base.Channel.GetAllWorkerAsync();
        }
        
        public System.Data.DataTable GetAllWorkerByDepartment(string departmentName) {
            return base.Channel.GetAllWorkerByDepartment(departmentName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllWorkerByDepartmentAsync(string departmentName) {
            return base.Channel.GetAllWorkerByDepartmentAsync(departmentName);
        }
    }
}
